"""Weather and Downscaling Pydantic Schemas."""
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List

class PanchayatSummary(BaseModel):
    id: str
    name: str
    block: str
    climate_zone: str
    climate_zone_source: str = "project_derived_agro_climatic_classification"
    elevation_m: float
    latitude: float
    longitude: float

class CoarseWeatherInput(BaseModel):
    coarse_rainfall_mm: float
    coarse_tmax_c: float
    coarse_tmin_c: float
    date: str
    weather_grid_latitude: float
    weather_grid_longitude: float
    grid_distance_km: float

class RawPrediction(BaseModel):
    rainfall_mm: float
    tmax_c: float
    tmin_c: float

class DonorDetails(BaseModel):
    id: str
    name: str
    climate_zone: str
    similarity_score: float
    distance_km: float
    terrain_comparison: Dict[str, Any]

class CorrectionDetails(BaseModel):
    rainfall_correction_mm: float
    tmax_correction_c: float
    tmin_correction_c: float
    status: str
    physical_adjustment_applied: bool = False
    physical_adjustment_notes: Optional[str] = None
    notes: str

class FinalPrediction(BaseModel):
    rainfall_mm: float
    tmax_c: float
    tmin_c: float
    diurnal_range_c: float

class ConfidenceDetails(BaseModel):
    score: float
    level: str
    score_type: str = "prototype_heuristic_confidence"
    training_status: str = "represented_in_training"
    explanation: str
    components: Dict[str, float]

class PipelineMetadata(BaseModel):
    model_type: str = "RandomForestRegressor"
    model_version: str = "v1.0"
    target_source: str = "synthetic_training_target"
    scientific_status: str = "prototype_not_real_world_validated"
    disclaimer: str = (
        "These predictions are generated by prototype models trained on synthetic local targets. "
        "They demonstrate the downscaling and terrain transfer learning architecture, but do not "
        "establish validated real-world meteorological forecast accuracy."
    )

class PanchayatDownscaleResponse(BaseModel):
    panchayat: PanchayatSummary
    input_weather: CoarseWeatherInput
    raw_prediction: RawPrediction
    donor: DonorDetails
    correction: CorrectionDetails
    final_prediction: FinalPrediction
    confidence: ConfidenceDetails
    metadata: PipelineMetadata
